### ISSUE TITLE
BTicino OpenWebNet [WARN ] [penwebnet.message.OpenMessageFactory] - ##openwebnet## WHO IS NOT SUPPORTED: WHO=AUTOMATION frame=*2*0*31#4#01##

### ISSUE THREAD

**Issue by Rob-VF** [mvalla/openhab-openwebnet#1]
Hello Massimo,

I successfully manage a BTicino SCS Bus system with more than 200 devices using OpenHab (1).

Trying openhab 2 I found org.openhab.binding.openwebnet-2.3.0-b4.jar as the only one allowing to scan the bus successfully.

After SCS gateway creation (I have a F454 last firmware update) I can scan the entire bus andall seems ok but.. there are some "not supported" as warning (error ignored) since a not ignored warning is found, and the communication with gateway stuck there.

Probably will be necessary to ignore that message too, please find following an ignored and the stucking one messages.

IGNORED:

[ERROR] [bnet.handler.OpenWebNetDeviceHandler] - ==OWN:DeviceHandler== updateLightOnOffState() NOT SUPPORTED OWN LIGHTING COMMAND for thing openwebnet:bus_on_off_switch:fde3ae4d:88h4h03, ignoring it. Frame=<*1*39*88#4#03##>

STUCKING (no more status updates rx):

[WARN ] [penwebnet.message.OpenMessageFactory] - ##openwebnet## WHO IS NOT SUPPORTED: WHO=AUTOMATION frame=*2*0*31#4#01##

**Comment by mvalla** [comment]
Thanks for the feedback.

- regarding the ignored command, if you confirm the command is `*1*39*88#4#03##`, I could not find any reference on the OpenWebNet specification about what command `WHAT=39` is about. Could you provide some more information about what this command is and what is its function? Which device is addressed `88#4#03` in your setup?

- regarding `*2*0*31#4#01##` this is an automation event that is not currently supported.
The bug is that if unsupported events are received, monitoring stops. This will be solved in the next release.

Massi

**Comment by Rob-VF** [comment]
Item is a light

*1*0*88#4#03##

I found on logs:

*1*39*88#4#03## and *1*34*88#4#03## and *1*89*88#4#03## also: could it be a dimmer?

In case of a malformed message on bus or “anything not supported” isn’t better to ignore it instead of to stop monitoring?

Regards

Roberto

**Comment by mvalla** [comment]
Sorry, but according to the official [OpenWebNet documentation](https://www.myopen-legrandgroup.com/developers/) , for Lighting (WHO=2), WHAT=39, 34 and 89 are _not defined_.
Can you please indentify the model of the device (form BTicino/Legrand catalogue) that creates the event, what conditions triggers the event or provide some official documentation that refers to these type of events?
Bye
Massimo

**Comment by Rob-VF** [comment]
Hello Massimo,

the module is a F411/4 and it can be possibile that the log itself is malformed: I suggest anyway that “not defined” or “not supported” don’t mean a service stop.

R

**Comment by mvalla** [comment]
Issue solved in v. beta5 of the binding
